/*
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2021-03-20
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.CreateCoinsTransactionFromAddressForWholeAmountRIRecipientsInner;
import org.openapitools.client.model.CreateCoinsTransactionFromAddressForWholeAmountRISenders;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateCoinsTransactionFromAddressForWholeAmountRI
 */
public class CreateCoinsTransactionFromAddressForWholeAmountRITest {
    private final CreateCoinsTransactionFromAddressForWholeAmountRI model = new CreateCoinsTransactionFromAddressForWholeAmountRI();

    /**
     * Model tests for CreateCoinsTransactionFromAddressForWholeAmountRI
     */
    @Test
    public void testCreateCoinsTransactionFromAddressForWholeAmountRI() {
        // TODO: test CreateCoinsTransactionFromAddressForWholeAmountRI
    }

    /**
     * Test the property 'callbackSecretKey'
     */
    @Test
    public void callbackSecretKeyTest() {
        // TODO: test callbackSecretKey
    }

    /**
     * Test the property 'callbackUrl'
     */
    @Test
    public void callbackUrlTest() {
        // TODO: test callbackUrl
    }

    /**
     * Test the property 'feePriority'
     */
    @Test
    public void feePriorityTest() {
        // TODO: test feePriority
    }

    /**
     * Test the property 'note'
     */
    @Test
    public void noteTest() {
        // TODO: test note
    }

    /**
     * Test the property 'recipients'
     */
    @Test
    public void recipientsTest() {
        // TODO: test recipients
    }

    /**
     * Test the property 'senders'
     */
    @Test
    public void sendersTest() {
        // TODO: test senders
    }

    /**
     * Test the property 'transactionRequestId'
     */
    @Test
    public void transactionRequestIdTest() {
        // TODO: test transactionRequestId
    }

    /**
     * Test the property 'transactionRequestStatus'
     */
    @Test
    public void transactionRequestStatusTest() {
        // TODO: test transactionRequestStatus
    }

}
