/*
 * Crypto APIs
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: bizdev@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GetContractDetailsByAddressResponseItem
 */
public class GetContractDetailsByAddressResponseItemTest {
    private final GetContractDetailsByAddressResponseItem model = new GetContractDetailsByAddressResponseItem();

    /**
     * Model tests for GetContractDetailsByAddressResponseItem
     */
    @Test
    public void testGetContractDetailsByAddressResponseItem() {
        // TODO: test GetContractDetailsByAddressResponseItem
    }

    /**
     * Test the property 'confirmedBalance'
     */
    @Test
    public void confirmedBalanceTest() {
        // TODO: test confirmedBalance
    }

    /**
     * Test the property 'creatorAddress'
     */
    @Test
    public void creatorAddressTest() {
        // TODO: test creatorAddress
    }

    /**
     * Test the property 'tokenDecimals'
     */
    @Test
    public void tokenDecimalsTest() {
        // TODO: test tokenDecimals
    }

    /**
     * Test the property 'tokenName'
     */
    @Test
    public void tokenNameTest() {
        // TODO: test tokenName
    }

    /**
     * Test the property 'tokenSymbol'
     */
    @Test
    public void tokenSymbolTest() {
        // TODO: test tokenSymbol
    }

    /**
     * Test the property 'tokenType'
     */
    @Test
    public void tokenTypeTest() {
        // TODO: test tokenType
    }

    /**
     * Test the property 'tokensBalance'
     */
    @Test
    public void tokensBalanceTest() {
        // TODO: test tokensBalance
    }

    /**
     * Test the property 'totalSupply'
     */
    @Test
    public void totalSupplyTest() {
        // TODO: test totalSupply
    }

}
