/*
 * CryptoAPIs
 * Crypto APIs is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2021-03-20
 * Contact: developers@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import io.cryptoapis.sdk.JSON;

/**
 * Tron
 */
@ApiModel(description = "Tron")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-12T15:09:18.638874Z[Etc/UTC]")
public class GetBlockDetailsByBlockHashFromCallbackRIBST {
  public static final String SERIALIZED_NAME_BANDWIDTH_USED = "bandwidthUsed";
  @SerializedName(SERIALIZED_NAME_BANDWIDTH_USED)
  private String bandwidthUsed;

  public static final String SERIALIZED_NAME_BURNED_TRX = "burnedTrx";
  @SerializedName(SERIALIZED_NAME_BURNED_TRX)
  private String burnedTrx;

  public static final String SERIALIZED_NAME_ENERGY_USED = "energyUsed";
  @SerializedName(SERIALIZED_NAME_ENERGY_USED)
  private String energyUsed;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  private Integer size;

  public GetBlockDetailsByBlockHashFromCallbackRIBST() { 
  }

  public GetBlockDetailsByBlockHashFromCallbackRIBST bandwidthUsed(String bandwidthUsed) {
    
    this.bandwidthUsed = bandwidthUsed;
    return this;
  }

   /**
   * Represents the bandwidth used for the transaction.
   * @return bandwidthUsed
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Represents the bandwidth used for the transaction.")

  public String getBandwidthUsed() {
    return bandwidthUsed;
  }


  public void setBandwidthUsed(String bandwidthUsed) {
    this.bandwidthUsed = bandwidthUsed;
  }


  public GetBlockDetailsByBlockHashFromCallbackRIBST burnedTrx(String burnedTrx) {
    
    this.burnedTrx = burnedTrx;
    return this;
  }

   /**
   * Represents the block burned TRX.
   * @return burnedTrx
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Represents the block burned TRX.")

  public String getBurnedTrx() {
    return burnedTrx;
  }


  public void setBurnedTrx(String burnedTrx) {
    this.burnedTrx = burnedTrx;
  }


  public GetBlockDetailsByBlockHashFromCallbackRIBST energyUsed(String energyUsed) {
    
    this.energyUsed = energyUsed;
    return this;
  }

   /**
   * Representats the used energy for the transaction.
   * @return energyUsed
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Representats the used energy for the transaction.")

  public String getEnergyUsed() {
    return energyUsed;
  }


  public void setEnergyUsed(String energyUsed) {
    this.energyUsed = energyUsed;
  }


  public GetBlockDetailsByBlockHashFromCallbackRIBST size(Integer size) {
    
    this.size = size;
    return this;
  }

   /**
   * Represents the total size of the block in Bytes.
   * @return size
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Represents the total size of the block in Bytes.")

  public Integer getSize() {
    return size;
  }


  public void setSize(Integer size) {
    this.size = size;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetBlockDetailsByBlockHashFromCallbackRIBST getBlockDetailsByBlockHashFromCallbackRIBST = (GetBlockDetailsByBlockHashFromCallbackRIBST) o;
    return Objects.equals(this.bandwidthUsed, getBlockDetailsByBlockHashFromCallbackRIBST.bandwidthUsed) &&
        Objects.equals(this.burnedTrx, getBlockDetailsByBlockHashFromCallbackRIBST.burnedTrx) &&
        Objects.equals(this.energyUsed, getBlockDetailsByBlockHashFromCallbackRIBST.energyUsed) &&
        Objects.equals(this.size, getBlockDetailsByBlockHashFromCallbackRIBST.size);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bandwidthUsed, burnedTrx, energyUsed, size);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetBlockDetailsByBlockHashFromCallbackRIBST {\n");
    sb.append("    bandwidthUsed: ").append(toIndentedString(bandwidthUsed)).append("\n");
    sb.append("    burnedTrx: ").append(toIndentedString(burnedTrx)).append("\n");
    sb.append("    energyUsed: ").append(toIndentedString(energyUsed)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("bandwidthUsed");
    openapiFields.add("burnedTrx");
    openapiFields.add("energyUsed");
    openapiFields.add("size");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("bandwidthUsed");
    openapiRequiredFields.add("burnedTrx");
    openapiRequiredFields.add("energyUsed");
    openapiRequiredFields.add("size");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to GetBlockDetailsByBlockHashFromCallbackRIBST
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (GetBlockDetailsByBlockHashFromCallbackRIBST.openapiRequiredFields.isEmpty()) {
          return;
        } else { // has required fields
          throw new IllegalArgumentException(String.format("The required field(s) %s in GetBlockDetailsByBlockHashFromCallbackRIBST is not found in the empty JSON string", GetBlockDetailsByBlockHashFromCallbackRIBST.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!GetBlockDetailsByBlockHashFromCallbackRIBST.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GetBlockDetailsByBlockHashFromCallbackRIBST` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : GetBlockDetailsByBlockHashFromCallbackRIBST.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (jsonObj.get("bandwidthUsed") != null && !jsonObj.get("bandwidthUsed").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bandwidthUsed` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bandwidthUsed").toString()));
      }
      if (jsonObj.get("burnedTrx") != null && !jsonObj.get("burnedTrx").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `burnedTrx` to be a primitive type in the JSON string but got `%s`", jsonObj.get("burnedTrx").toString()));
      }
      if (jsonObj.get("energyUsed") != null && !jsonObj.get("energyUsed").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `energyUsed` to be a primitive type in the JSON string but got `%s`", jsonObj.get("energyUsed").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GetBlockDetailsByBlockHashFromCallbackRIBST.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GetBlockDetailsByBlockHashFromCallbackRIBST' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GetBlockDetailsByBlockHashFromCallbackRIBST> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GetBlockDetailsByBlockHashFromCallbackRIBST.class));

       return (TypeAdapter<T>) new TypeAdapter<GetBlockDetailsByBlockHashFromCallbackRIBST>() {
           @Override
           public void write(JsonWriter out, GetBlockDetailsByBlockHashFromCallbackRIBST value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GetBlockDetailsByBlockHashFromCallbackRIBST read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of GetBlockDetailsByBlockHashFromCallbackRIBST given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of GetBlockDetailsByBlockHashFromCallbackRIBST
  * @throws IOException if the JSON string is invalid with respect to GetBlockDetailsByBlockHashFromCallbackRIBST
  */
  public static GetBlockDetailsByBlockHashFromCallbackRIBST fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GetBlockDetailsByBlockHashFromCallbackRIBST.class);
  }

 /**
  * Convert an instance of GetBlockDetailsByBlockHashFromCallbackRIBST to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

