/*
 * Crypto APIs
 * Crypto APIs 2.0 is a complex and innovative infrastructure layer that radically simplifies the development of any Blockchain and Crypto related applications. Organized around REST, Crypto APIs 2.0 can assist both novice Bitcoin/Ethereum enthusiasts and crypto experts with the development of their blockchain applications. Crypto APIs 2.0 provides unified endpoints and data, raw data, automatic tokens and coins forwardings, callback functionalities, and much more.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: bizdev@cryptoapis.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.GetXRPRippleTransactionDetailsByTransactionIDResponseItemRecipients;
import org.openapitools.client.model.GetXRPRippleTransactionDetailsByTransactionIDResponseItemSenders;
import org.openapitools.client.model.ListXRPRippleTransactionsByAddressResponseItemFee;
import org.openapitools.client.model.ListXRPRippleTransactionsByAddressResponseItemOffer;
import org.openapitools.client.model.ListXRPRippleTransactionsByAddressResponseItemReceive;
import org.openapitools.client.model.ListXRPRippleTransactionsByAddressResponseItemValue;

/**
 * ListXRPRippleTransactionsByAddressResponseItem
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-21T16:59:17.199745Z[Etc/UTC]")
public class ListXRPRippleTransactionsByAddressResponseItem {
  public static final String SERIALIZED_NAME_ADDITIONAL_DATA = "additionalData";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_DATA)
  private String additionalData;

  public static final String SERIALIZED_NAME_INDEX = "index";
  @SerializedName(SERIALIZED_NAME_INDEX)
  private Integer index;

  public static final String SERIALIZED_NAME_MINED_IN_BLOCK_HASH = "minedInBlockHash";
  @SerializedName(SERIALIZED_NAME_MINED_IN_BLOCK_HASH)
  private String minedInBlockHash;

  public static final String SERIALIZED_NAME_MINED_IN_BLOCK_HEIGHT = "minedInBlockHeight";
  @SerializedName(SERIALIZED_NAME_MINED_IN_BLOCK_HEIGHT)
  private Integer minedInBlockHeight;

  public static final String SERIALIZED_NAME_RECIPIENTS = "recipients";
  @SerializedName(SERIALIZED_NAME_RECIPIENTS)
  private List<GetXRPRippleTransactionDetailsByTransactionIDResponseItemRecipients> recipients = new ArrayList<GetXRPRippleTransactionDetailsByTransactionIDResponseItemRecipients>();

  public static final String SERIALIZED_NAME_SENDERS = "senders";
  @SerializedName(SERIALIZED_NAME_SENDERS)
  private List<GetXRPRippleTransactionDetailsByTransactionIDResponseItemSenders> senders = new ArrayList<GetXRPRippleTransactionDetailsByTransactionIDResponseItemSenders>();

  public static final String SERIALIZED_NAME_SEQUENCE = "sequence";
  @SerializedName(SERIALIZED_NAME_SEQUENCE)
  private Integer sequence;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private Integer timestamp;

  public static final String SERIALIZED_NAME_TRANSACTION_HASH = "transactionHash";
  @SerializedName(SERIALIZED_NAME_TRANSACTION_HASH)
  private String transactionHash;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_FEE = "fee";
  @SerializedName(SERIALIZED_NAME_FEE)
  private ListXRPRippleTransactionsByAddressResponseItemFee fee;

  public static final String SERIALIZED_NAME_OFFER = "offer";
  @SerializedName(SERIALIZED_NAME_OFFER)
  private ListXRPRippleTransactionsByAddressResponseItemOffer offer;

  public static final String SERIALIZED_NAME_RECEIVE = "receive";
  @SerializedName(SERIALIZED_NAME_RECEIVE)
  private ListXRPRippleTransactionsByAddressResponseItemReceive receive;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  private ListXRPRippleTransactionsByAddressResponseItemValue value;


  public ListXRPRippleTransactionsByAddressResponseItem additionalData(String additionalData) {
    
    this.additionalData = additionalData;
    return this;
  }

   /**
   * Represents any additional data that may be needed.
   * @return additionalData
  **/
  @ApiModelProperty(required = true, value = "Represents any additional data that may be needed.")

  public String getAdditionalData() {
    return additionalData;
  }


  public void setAdditionalData(String additionalData) {
    this.additionalData = additionalData;
  }


  public ListXRPRippleTransactionsByAddressResponseItem index(Integer index) {
    
    this.index = index;
    return this;
  }

   /**
   * Represents the index position of the transaction in the block.
   * @return index
  **/
  @ApiModelProperty(example = "3", required = true, value = "Represents the index position of the transaction in the block.")

  public Integer getIndex() {
    return index;
  }


  public void setIndex(Integer index) {
    this.index = index;
  }


  public ListXRPRippleTransactionsByAddressResponseItem minedInBlockHash(String minedInBlockHash) {
    
    this.minedInBlockHash = minedInBlockHash;
    return this;
  }

   /**
   * Represents the hash of the block where this transaction was mined/confirmed for first time. The hash is defined as a cryptographic digital fingerprint made by hashing the block header twice through the SHA256 algorithm.
   * @return minedInBlockHash
  **/
  @ApiModelProperty(example = "3dff3ab3697a0a3116062a92a499dc7b5c9c777b2035f79bb906894972d4573d", required = true, value = "Represents the hash of the block where this transaction was mined/confirmed for first time. The hash is defined as a cryptographic digital fingerprint made by hashing the block header twice through the SHA256 algorithm.")

  public String getMinedInBlockHash() {
    return minedInBlockHash;
  }


  public void setMinedInBlockHash(String minedInBlockHash) {
    this.minedInBlockHash = minedInBlockHash;
  }


  public ListXRPRippleTransactionsByAddressResponseItem minedInBlockHeight(Integer minedInBlockHeight) {
    
    this.minedInBlockHeight = minedInBlockHeight;
    return this;
  }

   /**
   * Represents the hight of the block where this transaction was mined/confirmed for first time. The height is defined as the number of blocks in the blockchain preceding this specific block.
   * @return minedInBlockHeight
  **/
  @ApiModelProperty(example = "15949067", required = true, value = "Represents the hight of the block where this transaction was mined/confirmed for first time. The height is defined as the number of blocks in the blockchain preceding this specific block.")

  public Integer getMinedInBlockHeight() {
    return minedInBlockHeight;
  }


  public void setMinedInBlockHeight(Integer minedInBlockHeight) {
    this.minedInBlockHeight = minedInBlockHeight;
  }


  public ListXRPRippleTransactionsByAddressResponseItem recipients(List<GetXRPRippleTransactionDetailsByTransactionIDResponseItemRecipients> recipients) {
    
    this.recipients = recipients;
    return this;
  }

  public ListXRPRippleTransactionsByAddressResponseItem addRecipientsItem(GetXRPRippleTransactionDetailsByTransactionIDResponseItemRecipients recipientsItem) {
    this.recipients.add(recipientsItem);
    return this;
  }

   /**
   * Represents an object of addresses that receive the transactions.
   * @return recipients
  **/
  @ApiModelProperty(required = true, value = "Represents an object of addresses that receive the transactions.")

  public List<GetXRPRippleTransactionDetailsByTransactionIDResponseItemRecipients> getRecipients() {
    return recipients;
  }


  public void setRecipients(List<GetXRPRippleTransactionDetailsByTransactionIDResponseItemRecipients> recipients) {
    this.recipients = recipients;
  }


  public ListXRPRippleTransactionsByAddressResponseItem senders(List<GetXRPRippleTransactionDetailsByTransactionIDResponseItemSenders> senders) {
    
    this.senders = senders;
    return this;
  }

  public ListXRPRippleTransactionsByAddressResponseItem addSendersItem(GetXRPRippleTransactionDetailsByTransactionIDResponseItemSenders sendersItem) {
    this.senders.add(sendersItem);
    return this;
  }

   /**
   * Represents an object of addresses that provide the funds.
   * @return senders
  **/
  @ApiModelProperty(required = true, value = "Represents an object of addresses that provide the funds.")

  public List<GetXRPRippleTransactionDetailsByTransactionIDResponseItemSenders> getSenders() {
    return senders;
  }


  public void setSenders(List<GetXRPRippleTransactionDetailsByTransactionIDResponseItemSenders> senders) {
    this.senders = senders;
  }


  public ListXRPRippleTransactionsByAddressResponseItem sequence(Integer sequence) {
    
    this.sequence = sequence;
    return this;
  }

   /**
   * Defines the transaction input&#39;s sequence as an integer, which is is used when transactions are replaced with newer versions before LockTime.
   * @return sequence
  **/
  @ApiModelProperty(example = "39673", required = true, value = "Defines the transaction input's sequence as an integer, which is is used when transactions are replaced with newer versions before LockTime.")

  public Integer getSequence() {
    return sequence;
  }


  public void setSequence(Integer sequence) {
    this.sequence = sequence;
  }


  public ListXRPRippleTransactionsByAddressResponseItem status(String status) {
    
    this.status = status;
    return this;
  }

   /**
   * Defines the status of the transaction.
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Defines the status of the transaction.")

  public String getStatus() {
    return status;
  }


  public void setStatus(String status) {
    this.status = status;
  }


  public ListXRPRippleTransactionsByAddressResponseItem timestamp(Integer timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Defines the exact date/time in Unix Timestamp when this transaction was mined, confirmed or first seen in Mempool, if it is unconfirmed.
   * @return timestamp
  **/
  @ApiModelProperty(example = "4256894", required = true, value = "Defines the exact date/time in Unix Timestamp when this transaction was mined, confirmed or first seen in Mempool, if it is unconfirmed.")

  public Integer getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(Integer timestamp) {
    this.timestamp = timestamp;
  }


  public ListXRPRippleTransactionsByAddressResponseItem transactionHash(String transactionHash) {
    
    this.transactionHash = transactionHash;
    return this;
  }

   /**
   * Represents the hash of the XRP transaction.
   * @return transactionHash
  **/
  @ApiModelProperty(example = "33684d38ccf56f5b10a25e60b11b251abe6288f41aadd03c7596dced895b282a", required = true, value = "Represents the hash of the XRP transaction.")

  public String getTransactionHash() {
    return transactionHash;
  }


  public void setTransactionHash(String transactionHash) {
    this.transactionHash = transactionHash;
  }


  public ListXRPRippleTransactionsByAddressResponseItem type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Specifies the type of the transaction.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Specifies the type of the transaction.")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public ListXRPRippleTransactionsByAddressResponseItem fee(ListXRPRippleTransactionsByAddressResponseItemFee fee) {
    
    this.fee = fee;
    return this;
  }

   /**
   * Get fee
   * @return fee
  **/
  @ApiModelProperty(required = true, value = "")

  public ListXRPRippleTransactionsByAddressResponseItemFee getFee() {
    return fee;
  }


  public void setFee(ListXRPRippleTransactionsByAddressResponseItemFee fee) {
    this.fee = fee;
  }


  public ListXRPRippleTransactionsByAddressResponseItem offer(ListXRPRippleTransactionsByAddressResponseItemOffer offer) {
    
    this.offer = offer;
    return this;
  }

   /**
   * Get offer
   * @return offer
  **/
  @ApiModelProperty(required = true, value = "")

  public ListXRPRippleTransactionsByAddressResponseItemOffer getOffer() {
    return offer;
  }


  public void setOffer(ListXRPRippleTransactionsByAddressResponseItemOffer offer) {
    this.offer = offer;
  }


  public ListXRPRippleTransactionsByAddressResponseItem receive(ListXRPRippleTransactionsByAddressResponseItemReceive receive) {
    
    this.receive = receive;
    return this;
  }

   /**
   * Get receive
   * @return receive
  **/
  @ApiModelProperty(required = true, value = "")

  public ListXRPRippleTransactionsByAddressResponseItemReceive getReceive() {
    return receive;
  }


  public void setReceive(ListXRPRippleTransactionsByAddressResponseItemReceive receive) {
    this.receive = receive;
  }


  public ListXRPRippleTransactionsByAddressResponseItem value(ListXRPRippleTransactionsByAddressResponseItemValue value) {
    
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(required = true, value = "")

  public ListXRPRippleTransactionsByAddressResponseItemValue getValue() {
    return value;
  }


  public void setValue(ListXRPRippleTransactionsByAddressResponseItemValue value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListXRPRippleTransactionsByAddressResponseItem listXRPRippleTransactionsByAddressResponseItem = (ListXRPRippleTransactionsByAddressResponseItem) o;
    return Objects.equals(this.additionalData, listXRPRippleTransactionsByAddressResponseItem.additionalData) &&
        Objects.equals(this.index, listXRPRippleTransactionsByAddressResponseItem.index) &&
        Objects.equals(this.minedInBlockHash, listXRPRippleTransactionsByAddressResponseItem.minedInBlockHash) &&
        Objects.equals(this.minedInBlockHeight, listXRPRippleTransactionsByAddressResponseItem.minedInBlockHeight) &&
        Objects.equals(this.recipients, listXRPRippleTransactionsByAddressResponseItem.recipients) &&
        Objects.equals(this.senders, listXRPRippleTransactionsByAddressResponseItem.senders) &&
        Objects.equals(this.sequence, listXRPRippleTransactionsByAddressResponseItem.sequence) &&
        Objects.equals(this.status, listXRPRippleTransactionsByAddressResponseItem.status) &&
        Objects.equals(this.timestamp, listXRPRippleTransactionsByAddressResponseItem.timestamp) &&
        Objects.equals(this.transactionHash, listXRPRippleTransactionsByAddressResponseItem.transactionHash) &&
        Objects.equals(this.type, listXRPRippleTransactionsByAddressResponseItem.type) &&
        Objects.equals(this.fee, listXRPRippleTransactionsByAddressResponseItem.fee) &&
        Objects.equals(this.offer, listXRPRippleTransactionsByAddressResponseItem.offer) &&
        Objects.equals(this.receive, listXRPRippleTransactionsByAddressResponseItem.receive) &&
        Objects.equals(this.value, listXRPRippleTransactionsByAddressResponseItem.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalData, index, minedInBlockHash, minedInBlockHeight, recipients, senders, sequence, status, timestamp, transactionHash, type, fee, offer, receive, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListXRPRippleTransactionsByAddressResponseItem {\n");
    sb.append("    additionalData: ").append(toIndentedString(additionalData)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    minedInBlockHash: ").append(toIndentedString(minedInBlockHash)).append("\n");
    sb.append("    minedInBlockHeight: ").append(toIndentedString(minedInBlockHeight)).append("\n");
    sb.append("    recipients: ").append(toIndentedString(recipients)).append("\n");
    sb.append("    senders: ").append(toIndentedString(senders)).append("\n");
    sb.append("    sequence: ").append(toIndentedString(sequence)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    transactionHash: ").append(toIndentedString(transactionHash)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    offer: ").append(toIndentedString(offer)).append("\n");
    sb.append("    receive: ").append(toIndentedString(receive)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

